version: "3.8"

services:
  fastapi_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    restart: always
    networks:
      - app_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  app_network:
    driver: bridge
